name: Flutter Web Deploy

# Запускаем этот сценарий при каждом пуше в ветку main (или master)
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Загружаем код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Используем стабильную ветку Flutter

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: flutter pub get

      # 4. Собираем Web-версию приложения
      # Замените 'ваш_github_username/название_репозитория' на ваши данные
      - name: Build Web
        run: flutter build web --base-href "visitor_log"

      # 5. Публикуем результат в ветку gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web